input-output-hk/devx

flake.nix

This is necessary as we otherwise clash beween static/dynamic libraries (and their paths) as encoded in the cabal store and then leak into static builds, or vice versa.

Make sure ~/.cabal ends up in different locations

---

flake.nix

Drop ghc-8.5.6 and ghc-8.8.4

---

flake.nix

This shell has been tested on https://github.com/Quviq/quickcheck-contractmodel and it works (even on WLS2).
The developers are asking for a shell prompt, so that they know they are inside the shell.
This prompt simply prints the current directory in yellow

Export a colored PS1 prompt in the shell

---

haskell/nix-shell/action.yml

Is this up to date? I think `ghc924` is part of the GHC version the shell opt out https://github.com/input-output-hk/devx/blob/main/flake.nix#L103 as described here https://github.com/input-output-hk/devx/issues/23

Update `haskell/nix-shell/action.yml` from `ghc924`

---

.github/workflows/main.yml
extra/ghcr-upload.sh
flake.nix

GHA should be able to download the required files from the nix cache populated by hydra.  If it cannot DL what it needs, it is better to have it fail instead of wasting resources trying a build that will probably eventually run out of disk space anyway.

Avoid building in GHA

---

.github/workflows/main.yml
extra/ghcr-upload.sh

This reverts commit 43d7fb43e58a8bc4e35e72f00786633e3387c4d8.
It turns out that we need to build the `plan-nix` derivations as they are not cached.

Revert "Avoid building in GHA"

---

.github/workflows/codespace.yml

This as been tested to be working as expected [in this fork](https://github.com/yvan-sraka/devx/pkgs/container/devx-devcontainer)! I also had to [configure the default `GITHUB_TOKEN` permissions](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-the-default-github_token-permissions) of the repository.

Add `packages: write` permission to GA that build Codespace docker images

---

.github/workflows/codespace.yml
Dockerfile

This is apparently the default behavior chosen by Docker when `ARG` are defined before `FROM` … and indeed Docker don't bother you with any warning :)

Fix Codespace image generation (always empty Dockerfile `ARG`…)

---

extra/ghcr-upload.sh

The motivation is to detect the faulty closures by failing in CI, rather than silently uploading them to ghcr.io

Check while caling `ghcr-upload.sh` that closure contains `devx` shell rc derivation

---

.github/workflows/codespace.yml

I'm not sure of that one, since the GA will be run on an `x86_64` machine, right?

Add `aarch64-linux` to GitHub Codespace Action to support macOS M1/M2 VSCode DevContainers

---

tool-map.nix

```
% nix develop ".#ghc962"
trace: No HLint. Not yet compatible with ghc962
_____ _____ _____    _____         _       _ _    _____ _       _ _ 
|     |     |   __|  |  |  |___ ___| |_ ___| | |  |   __| |_ ___| | |
|-   -|  |  |  |  |  |     | .'|_ -| '_| -_| | |  |__   |   | -_| | |
|_____|_____|_____|  |__|__|__,|___|_,_|___|_|_|  |_____|_|_|___|_|_|
Revision (input-output-hk/devx): 63135bc983b8000fcd267843740f3cdad7bf8d75.
CABAL_DIR set to /Users/yvan/.cabal-devx
[~/IOHK/devx]$ haskell-language-server --version
2023-08-28T09:40:27.450883Z | Info | No log file specified; using stderr.
haskell-language-server version: 2.0.0.0 (GHC: 9.6.2) (PATH: /nix/store/jfbsphs6bqq52cs185ynxmzc5h55prb1-haskell-language-server-exe-haskell-language-server-2.0.0.0/bin/haskell-language-server)
```
It …

Update HLS to version 2.0

---

cross-windows.nix

When cross compiling for windows use set the cabal flag `--test-wrapper` to point at a script that runs the test in wine.

Run tests with wine by default

---

cross-js.nix
cross-windows.nix
flake.nix
quirks.nix
static.nix

```
% nix develop ".#ghc962-static-minimal"
_____ _____ _____    _____         _       _ _    _____ _       _ _ 
|     |     |   __|  |  |  |___ ___| |_ ___| | |  |   __| |_ ___| | |
|-   -|  |  |  |  |  |     | .'|_ -| '_| -_| | |  |__   |   | -_| | |
|_____|_____|_____|  |__|__|__,|___|_,_|___|_|_|  |_____|_|_|___|_|_|
_        _   _             _ _ _   _                   
_/\____   __| |_ __ _| |_(_)__   ___ __| (_) |_(_)___ _ _    ____/\_
>  <___| (_-<  _/ _` |  _| / _| / -_) _` | |  _| / _ \ ' \  |___>  <
\/|___| /__/\__\__,_|\__|_\__| \___\__,_|_|\__|_\___/_||_| |___|\/ 
Revision (input-output-hk/devx): 9fb95ac431622597fb663d5c00525bb42845bc51.
NOTE (macos): you can use fixup-nix-deps FILE, to fix iconv, ffi, and zlib dependencies that point to the /nix/store
CABAL_DIR set to …
```

Expose `CABAL_PROJECT_LOCAL_TEMPLATE` as a `/nix/store/` file

---

Dockerfile

... seems like `curl` should be available in DevContainer to use `chap`, otherwise:
```
[/workspaces/cardano-base]$ which curl
[/workspaces/cardano-base]$ cabal update
Warning: Caught exception during _mirrors lookup:user error (res_query(3)
failed)
Warning: No mirrors found for https://chap.intersectmbo.org/
user error (https not supported)
```
@andreabedini thoughts on that?

Fix #124: cabal update with CHaP fails inside Docker container

---

README.md
docs/bootstrap.sh
docs/direnv.md
flake.nix

Update `README.md` to rather suggest user to directly put the `extra-substituters` in `/etc/nix/nix.conf` and remove `nixConfig` attribute from the `flake.nix`.
[Rendered](https://github.com/input-output-hk/devx/blob/fix-116-do-not-recommend-to-change-trusted-users-anymore/README.md)

Fix #116: `trusted-users` allows running commands as root without password

---

.github/workflows/wait-and-upload.yml
Dockerfile
README.md

I also updated the README: [Rendered](https://github.com/input-output-hk/devx/blob/iog-full-devx-container/README.md#compilers-and-flavors)

Finish the `-iog-full` flavor by generating the corresponding `devx-container`

---

README.md

This is a follow-up to an issue encountered by @zeme-wana. He suggested that this information could be added to the README :)
[Rendered](https://github.com/input-output-hk/devx/blob/readme-devcontainer-tips/README.md#vscode-devcontainer--github-codespace-support)

Add instructions on how to use DevContainers outside of GitHub or VSCode

---

.github/workflows/cleanup.yml

There is a lot of old `devx-containers` https://github.com/input-output-hk/devx/pkgs/container/devx-devcontainer/versions?filters%5Bversion_type%5D=untagged that I believe we could GC with this automation

Add a simple GitHub Action that cleanup untagged `devx-container` daily

---

cross-js.nix
cross-windows.nix
dynamic.nix
quirks.nix
static.nix

As suggested by @angerman, in response to issues that @erikd and @sgillespie got while debugging [`db-sync` actions](https://github.com/IntersectMBO/cardano-db-sync/actions/runs/8517329880/job/23327725038?pr=1636).
The output looks like:
```
% export GITHUB_ACTIONS=true
% nix develop ".#ghc96"     
_____ _____ _____    _____         _       _ _    _____ _       _ _ 
|     |     |   __|  |  |  |___ ___| |_ ___| | |  |   __| |_ ___| | |
|-   -|  |  |  |  |  |     | .'|_ -| '_| -_| | |  |__   |   | -_| | |
|_____|_____|_____|  |__|__|__,|___|_,_|___|_|_|  |_____|_|_|___|_|_|
Revision (input-output-hk/devx): 6b241faf9b5ebe1fbbfbd56d0cf96867bf8477e9.
CABAL_DIR set to /Users/yvan/.cabal-devx
Hint: to reproduce this environment locally, use either:
$ nix develop …
```

Add hint to reproduce the devshell flavor locally if within GitHub Action

---

Dockerfile
README.md

Updates the `Dockerfile` used to create GitHub Codespace images to now preload the `$HOME/.cache` folder with artifacts from the corresponding repository's GitHub Actions. This aims to speed-up HLS startup in a fresh GitHub Codespace by leveraging previously built artifacts.
It's important to note that the cache download occurs when spawning a terminal in the Codespace, not during the image build process. The rationale behind this approach is to avoid building a unique Codespace image for each repository and to keep these images generic.
Additionally, if the artifacts are not found in the cache, the script will fail silently (considering adding a warning) since caching build artifacts is an optional, opt-in feature per repository. Also, note that caching is based on a "per commit" basis …

Improve GitHub Codespace First-Launch Time by Preloading `.cache`

---

.github/workflows/wait-and-upload.yml

https://github.com/input-output-hk/devx/actions/runs/8597748068

Fix `No space left on device` while building `devx-container` in GitHub Action

---

.github/workflows/wait-and-upload.yml
Dockerfile

e.g. `x86_64-linux.ghc96-jsfalse` rather than `x86_64-linux.ghc96-js` ...

Fix `codespace-upload` action that wrongly name `devx-containers`

---

quirks.nix

```
Revision (input-output-hk/devx): 0a5cefb55c8c41cbc6119370dfdb8d8f78832633. /nix/store/2nigzj6x6d0qkzqvvyf5604g0581r8z6-ghc810-env.sh: line 1937: CODESPACE_TOKEN: unbound variable CABAL_DIR set to /Users/runner/.cabal-devx
Notice: Hint: to reproduce this environment locally, use either: `nix develop github:input-output-hk/devx#ghc8107`, or `docker run -it -v $(pwd):/workspaces ghcr.io/input-output-hk/devx-devcontainer:x86_64-linux.ghc8107`
```

Fix `CODESPACE_TOKEN: unbound variable`

---

.github/workflows/main.yml
cross-js.nix
cross-windows.nix
dynamic.nix
flake.lock
flake.nix
static.nix
tool-map.nix

```
% nix flake lock --update-input haskellNix
warning: updating lock file '/Users/yvan/GitHub/devx/flake.lock':
• Updated input 'haskellNix':
'github:input-output-hk/haskell.nix/4589f9d34ee36f3f622177fcd665c2e7084308d1' (2023-10-16)
→ 'github:input-output-hk/haskell.nix/e8a8f03518ab36c8cc3418b3190d450af696a4ac' (2024-03-29)
• Added input 'haskellNix/ghc910X':
'git+https://gitlab.haskell.org/ghc/ghc?ref=ghc-9.10&rev=21e3f3250e88640087a1a60bee2cc113bf04509f' (2024-03-06)
• Added input 'haskellNix/ghc911':
'git+https://gitlab.haskell.org/ghc/ghc?ref=refs/heads/master&rev=e6bfb85c842edca36754bb8914e725fbaa1a83a6' (2024-03-12)
• Removed input 'haskellNix/ghc98X'
• Removed input 'haskellNix/ghc99'
• Updated input 'haskellNix/hackage': …
```

Fix #132: add support for GHC 9.6.4

---

.github/workflows/build-and-test.yml
.github/workflows/lints.yml
.github/workflows/wait-and-upload.yml

GH wants to move to node 20 instead of 16. This necessitates migrating @v3 actions to @v4.

No more Node.js 16

---

Dockerfile

Needs https://github.com/input-output-hk/actions/pull/19 to be merged first

Retrieve `~/.cabal-devx` and `~/.cache` from GHA cache in Codespaces

---

extra/ghcide-workaround.diff
tool-map.nix

c.f. https://github.com/haskell/haskell-language-server/issues/4046
The problem could be observed with this demo project https://github.com/sgillespie/cardano-dev-hls/tree/main

Patch "HLS stuck (init then no progress) since multi home support"

---

quirks.nix

```
/nix/store/1zcy75q3dr61bka5h4r8rf3kv8k18kw3-ghc96-iog-env.sh: line 1944: [: -v: unary operator expected
```
e.g. seen on https://github.com/IntersectMBO/cardano-node/actions/runs/8977554294/job/24656515205?pr=5817, in the Build all step.

Fix `[: -v: unary operator expected`

---

Dockerfile

```
mktemp: failed to create directory via template '/tmp/nix-shell.xsPtzA/nix-shell.XXXXXX': No such file or directory
```

Fix error: `failed to create directory via template '/tmp/nix-shell.XXXXXX/'`

---

flake.nix

Static shell variants are currently failing with
```
In file included from bigdecimal.h:14,
from bigdecimal.c:11:
missing.h:127:1: error: static declaration of 'rb_rational_num' follows non-static declaration
127 | rb_rational_num(VALUE rat)
| ^~~~~~~~~~~~~~~
```
But It's not important to use static ruby anyways, because we are interested in producing static artifacts, not the build tools themselves.
So, this change
* Removes static ruby in favor of the regular one
* Removes patches that fixes static ruby

fix: Use dynamic ruby even in static variants

---

dynamic.nix

* Use correct variant of optional/optionals
* Clean up formatting

Fix dependencies for iog-full flavor

---

flake.nix

I wish we could just rely on /bin/bash being recent enough.

Use nix-shell to launch the bash shell

---

dynamic.nix

Our GHC tooling needs git, so we'll add it to the closure.

add git tooling
